### ISSUE TITLE
getObjectsByType is not working

### ISSUE THREAD

**Issue by althaffe** [cosmicjs/cosmicjs-node#15]
bucket.getObjectsByType is returning a 404. The issue is with the api end-point. Latest commit replaces 'object-type' with 'objects-type' in the end-point. The former url 'https://api.cosmicjs.com/v1/{ bucket-slug }/object-type/{ object type }' is working properly.

**Comment by tonyspiro** [comment]
Thanks for finding this @althaffe.  It's now fixed.  Please check.

**Comment by althaffe** [comment]
It's working now :+1: 
It's best to setup some tests to avoid these issues in the future.
