### ISSUE TITLE
Add better querying support

### ISSUE THREAD

**Issue by althaffe** [cosmicjs/cosmicjs-node#16]
Currently, there seems to be no option for selecting the fields that should be included in the response during a getObject or seachObject call. To get a single metafield value from an object, the whole object needs to be downloaded. For simple objects, this doesn't add much overhead. But that's not the case when an object contains large descriptions, articles etc.
Similarly, should be able to select fields on connected objects too.

**Comment by tonyspiro** [comment]
Great suggestion for the REST API @althaffe, have you checked out the GraphQL API?  This does exactly that https://cosmicjs.com/docs/graphql

**Comment by althaffe** [comment]
Oh, didn't know GraphQL could do that. Thanks for the heads up.
