### ISSUE TITLE
sort not working for getObjects

### ISSUE THREAD

**Issue by AWolf81** [cosmicjs/cosmicjs-node#20]
In the [docs](https://cosmicjs.github.io/rest-api-docs/?javascript#get-objects) there is a `sort` property for `getObjects` but it looks like that's missing in the source code.

After adding

    if (params && params.sort) {
        endpoint += `&sort=${params.sort}`
    }

it's working.

Is this missing or can I do sorting differently?
I can add these lines to be consistent with the docs.

**Comment by tonyspiro** [comment]
Thanks for the find @AWolf81! Just published a patch (3.2.2) that includes this param.  Please confirm that it's working.

**Comment by AWolf81** [comment]
You're welcome.

Yes, your patch fixes the issue. Sorting is working with 3.2.2.

**Comment by tonyspiro** [comment]
👍
