### ISSUE TITLE
deleteObject not working - returns 'object not found'

### ISSUE THREAD

**Issue by AWolf81** [cosmicjs/cosmicjs-node#21]
Seems like the api endpoint is getting the `bucket_slug` instead of the object slug and that's why it is returning 'Object not found'.

In [line 272](https://github.com/cosmicjs/cosmicjs-node/blob/master/index.js#L272) bucket_config contains slug.

After changing that line to something like this `return axios.delete(endpoint, { data: Object.assign(bucket_config, {slug: params.slug}) })` deleting was working. Probably it would also work if bucket slug is removed from config before adding it to data.

**Comment by tonyspiro** [comment]
Thanks for the find @AWolf81!  This is now fixed in the latest version (3.2.3)
