### ISSUE TITLE
Vulnerability in axios< 0.21.1

### ISSUE THREAD

**Issue by debaraj-barua** [cosmicjs/cosmicjs-node#39]
Source: https://www.npmjs.com/advisories/1594

**Overview**

The axios NPM package before 0.21.1 contains a Server-Side Request Forgery (SSRF) vulnerability where an attacker is able to bypass a proxy by providing a URL that responds with a redirect to a restricted host or IP address.

**Remediation**

Upgrade to 0.21.1 or later.

**Comment by tonyspiro** [comment]
Thanks @debaraj-barua, this is done.
